language: R
cache: packages

pandoc_version: 2.3.1

env:
  global:
    - LANG=en_GB.UTF-8
    - LANGUAGE=en_GB.UTF-8
    - LC_CTYPE=en_GB.UTF-8
    - LC_NUMERIC=en_GB.UTF-8
    - LC_TIME=en_GB.UTF-8
    - LC_COLLATE=en_GB.UTF-8
    - LC_MONETARY=en_GB.UTF-8
    - LC_MESSAGES=en_GB.UTF-8
    - LC_PAPER=en_GB.UTF-8
    - LC_NAME=en_GB.UTF-8
    - LC_ADDRESS=en_GB.UTF-8
    - LC_TELEPHONE=en_GB.UTF-8
    - LC_MEASUREMENT=en_GB.UTF-8
    - LC_IDENTIFICATION=en_GB.UTF-8
    - LC_ALL=en_GB.UTF-8

addons:
  apt:
    packages:
    - cargo
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    
before_script:
  - sudo git clone https://github.com/ipython/xkcd-font.git /usr/share/fonts/xkcd-font
  - sudo fc-cache -f -v
  - Rscript -e 'sysfonts::font_add("xkcd", "xkcd.otf")'

script: Rscript -e 'rmarkdown::render(input = "IMDb_rating_analysis.Rmd")'

before_deploy: 
  - Rscript -e 'remotes::install_cran("pkgdown")'
  - Rscript -e 'source("https://raw.githubusercontent.com/mcanouil/DEV/master/R/deploy.R")'

deploy:
  provider: script
  script: Rscript -e 'deploy_site("IMDb_rating_analysis.Rmd", commit_message = "IMDbRating")'
  skip_cleanup: true

